name: lesliebishop
favicon: null
layout_spectrum: 0.44608160899952054
typography_spectrum: 0.9388694963417947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7330397164914757
  lightness: 0.82933085039258
  saturation: 0.029572617961093783
  rhythmicContrast: 0.4029108739923686
purpose: []
